name: Release

on:
  release:
    types: [released]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: cd src && npm install

      - name: Build
        run: cd src && npm run build

      - name: Run Tests
        run: cd src && npm run test

  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: cd src && npm install

      - name: Build
        run: cd src && npm run build

      - name: Publish
        run: cd src && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
